
title: Patrick McAndrew's CV
url: 'http://dev.so-sure.net:40080'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Patrick McAndrew
tagline: Seeking CTO Role for Funded Startup

#sidebar links
email: c@urgsystems.com
website: urg.name #do not add http://
linkedin: urg98
github: urg
twitter: '@urg98'

#Update all the sections by editing the files inside _includes folder.
